version: "3.8"

services:
  # Frontend client (Vite built, served by its own nginx in image)
  frontend:
    image: khanhlinh1605/superrice_frontend:latest
    container_name: frontend-app
    restart: unless-stopped
    networks:
      - app-network

  # Admin panel (CRA build served by nginx in image)
  admin:
    image: khanhlinh1605/superrice_admin:latest
    container_name: admin-app
    restart: unless-stopped
    networks:
      - app-network

  # Backend API (Express)
  backend:
    image: khanhlinh1605/superrice_backend:latest
    container_name: backend-api
    restart: unless-stopped
    env_file:
      - .env.backend
    environment:
      - PORT=5000
    networks:
      - app-network

  # Nginx reverse proxy (serves FE/Admin and proxies /api and /ai to backend)
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    depends_on:
      - frontend
      - admin
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/nginx/ssl:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
