version: "3.8"

services:
  # Frontend service
  frontend:
    image: khanhlinh1605/superrice_frontend:latest
    container_name: frontend-app
    restart: always
    ports:
      - "80"
    networks:
      - app-network

  # Nginx reverse proxy
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
        - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
