# STAGE 1: Build ứng dụng React/Vite với Node.js phiên bản 20
FROM node:20-alpine AS builder
WORKDIR /app
# Chỉ cần khai báo MỘT đối số để nhận toàn bộ file .env
ARG FRONTEND_ENV_CONTENT
# Ghi toàn bộ nội dung nhận được vào file .env
RUN echo "$FRONTEND_ENV_CONTENT" > .env
# Copy file quản lý package của npm
COPY package.json package-lock.json* ./
# Chạy lệnh cài đặt của npm
RUN npm ci
# Copy toàn bộ mã nguồn frontend
COPY . .
# Chạy lệnh build
RUN npm run build
# STAGE 2: Serve các file tĩnh bằng Nginx (Giữ nguyên)
FROM nginx:stable-alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/default.conf /etc/nginx/conf.d/
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]